import { Box, Grid } from '@mui/material'
import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/Banner'

export default function Home() {
  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box id="content-wrapper" sx={{backgroundColor:"#EEEEEE",top:"60px",position:"relative",width:"100%",height:"100vh"}}>
        <Banner/>
        <Box sx={{padding:"0px calc((100vw - 984px) / 2)"}}>HELLO</Box>
      </Box>

    </Box>
  )
}
